setup script for kotlin

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -3,50 +3,48 @@ default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 
 app:
   envs:
-    - GRADLE_BUILD_FILE_PATH: gradle file path
-    - GRADLEW_PATH: gradle path
-    # If you want to share this step into a StepLib
+    - GRADLE_BUILD_FILE_PATH: build.gradle
+    - GRADLEW_PATH: ./gradlew
     - BITRISE_STEP_ID: ktlint-step
-    - BITRISE_STEP_VERSION: "0.0.1"
-    - BITRISE_STEP_GIT_CLONE_URL: https://github.com/cisekluke/Ktlint-Bitrise-step
+    - BITRISE_STEP_VERSION: "0.1.0"
+    - BITRISE_STEP_GIT_CLONE_URL: https://github.com/cisekluke/TestBitrise
     - MY_STEPLIB_REPO_FORK_GIT_URL: $MY_STEPLIB_REPO_FORK_GIT_URL
 workflows:
   test:
     steps:
     - script:
         inputs:
-        - content: |
+        - content: |-
             #!/bin/bash
-            echo "Just an example 'secrets' print."
-            echo "The value of 'A_SECRET_PARAM' is: $A_SECRET_PARAM"
-#    - change-workdir:
-#        title: Switch working dir to test / _tmp dir
-#        description: |-
-#          To prevent step testing issues, like referencing relative
-#          files with just './some-file' in the step's code, which would
-#          work for testing the step from this directory directly
-#          but would break if the step is included in another `bitrise.yml`.
-#        run_if: true
-#        inputs:
-#        - path: ./_tmp
-#        - is_create_path: true
-    - path::./:
-        title: Step Test -version
-        description: |-
-          The example input has a default value,
-          you can overwrite it if you want to, just like we did below,
-          but the step would use the default value specified in the `step.yml`
-          file if you would not specify another value.
+            set -ex
+            rm -rf ./_tmp
+    - change-workdir:
+        title: Switch working dir to test / _tmp dir
         run_if: true
         inputs:
-          - ktlint_task: task
-  #      - example_step_input: Example Step Input's value
+        - path: ./_tmp
+        - is_create_path: true
+    - git-clone:
+        run_if: true
+        inputs:
+        - repository_url: $BITRISE_STEP_GIT_CLONE_URL
+        - clone_into_dir: ./
+        - commit: ""
+        - tag: ""
+        - branch: "master"
+        - pull_request_id: ""
+        - clone_depth: ""
+    - path::./:
+        title: Test Ktlint step
+        run_if: true
+        inputs:
+          - ktlint_task: ktlint
     - script:
         inputs:
         - content: |
             #!/bin/bash
-            echo "This output was generated by the Step (BITRISE_KTLINT_RESULT second): $BITRISE_KTLINT_RESULT"
-
+            echo "This output was generated by BITRISE_KTLINT_RESULT: $BITRISE_KTLINT_RESULT"
+            echo "This output was generated by BITRISE_KTLINT_ERRORS: $BITRISE_KTLINT_ERRORS"
 
   # ----------------------------------------------------------------
   # --- workflows to Share this step into a Step Library
